// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package spacetimedb

import (
	"github.com/clockworklabs/SpacetimeDB/crates/bindings-go/pkg/spacetimedb"
)

// EchoU8Args contains arguments for the echo_u8 reducer
type EchoU8Args struct {
	Id    uint32 `json:"id" bsatn:"id"`
	Value uint8  `json:"value" bsatn:"value"`
}

// EchoU8 is a SpacetimeDB reducer
// TODO: Implement your reducer logic here
func EchoU8(ctx *spacetimedb.ReducerContext, args EchoU8Args) error {
	// TODO: Add your reducer implementation here
	return nil
}

// RegisterEchoU8 registers the echo_u8 reducer with SpacetimeDB
func RegisterEchoU8() {
	spacetimedb.RegisterReducer("echo_u8", "EchoU8", func(ctx *spacetimedb.ReducerContext, args []byte) spacetimedb.ReducerResult {
		var parsedArgs EchoU8Args
		if err := spacetimedb.BsatnFromBytes(args, &parsedArgs); err != nil {
			return spacetimedb.ReducerResult{Error: err}
		}
		if err := EchoU8(ctx, parsedArgs); err != nil {
			return spacetimedb.ReducerResult{Error: err}
		}
		return spacetimedb.ReducerResult{}
	})
}
