// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package spacetimedb

import (
	"github.com/clockworklabs/SpacetimeDB/crates/bindings-go/pkg/spacetimedb"
)

// EchoVec2Args contains arguments for the echo_vec2 reducer
type EchoVec2Args struct {
	Id uint32 `json:"id" bsatn:"id"`
	X  int32  `json:"x" bsatn:"x"`
	Y  int32  `json:"y" bsatn:"y"`
}

// EchoVec2 is a SpacetimeDB reducer
// TODO: Implement your reducer logic here
func EchoVec2(ctx *spacetimedb.ReducerContext, args EchoVec2Args) error {
	// TODO: Add your reducer implementation here
	return nil
}

// RegisterEchoVec2 registers the echo_vec2 reducer with SpacetimeDB
func RegisterEchoVec2() {
	spacetimedb.RegisterReducer("echo_vec2", "EchoVec2", func(ctx *spacetimedb.ReducerContext, args []byte) spacetimedb.ReducerResult {
		var parsedArgs EchoVec2Args
		if err := spacetimedb.BsatnFromBytes(args, &parsedArgs); err != nil {
			return spacetimedb.ReducerResult{Error: err}
		}
		if err := EchoVec2(ctx, parsedArgs); err != nil {
			return spacetimedb.ReducerResult{Error: err}
		}
		return spacetimedb.ReducerResult{}
	})
}
