// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package spacetimedb

// RegisterModule registers all tables and reducers for this SpacetimeDB module
func RegisterModule() error {
	// Register the bsatn_test_result table
	if err := RegisterBsatnTestResult(); err != nil {
		return err
	}

	// Register reducers
	RegisterClearResults()
	RegisterEchoU8()
	RegisterEchoVec2()
	return nil
}

// init automatically registers the module when the package is imported
func init() {
	if err := RegisterModule(); err != nil {
		panic("Failed to register SpacetimeDB module: " + err.Error())
	}
}
