receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # Prometheus receiver to scrape SpacetimeDB metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'spacetimedb'
          scrape_interval: 10s
          static_configs:
            - targets: ['spacetimedb:9000']
              labels:
                service: 'spacetimedb'
                environment: 'development'
        
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8889']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 1s

  attributes:
    actions:
      - key: service.name
        value: spacetimedb
        action: upsert
      - key: service.namespace
        value: spacetimedb
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

  filter/metrics:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - spacetimedb.*
          - database.*
          - module.*
          - query.*
          - transaction.*
          - connection.*
          - system.*

  resource:
    attributes:
      - key: host.name
        from_attribute: HOSTNAME
        action: upsert
      - key: telemetry.sdk.name
        value: opentelemetry
        action: upsert
      - key: telemetry.sdk.language
        value: rust
        action: upsert

exporters:
  # File exporters for persistence and debugging
  file/traces:
    path: /data/traces/traces.jsonl
    format: json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 3

  file/metrics:
    path: /data/metrics/metrics.jsonl
    format: json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 3

  file/logs:
    path: /data/logs/logs.jsonl
    format: json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 3

  # Prometheus exporter for real-time metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      environment: development
      service: spacetimedb
    resource_to_telemetry_conversion:
      enabled: true

  # OTLP exporter for Jaeger
  otlp/jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Debug exporter for troubleshooting
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes, resource]
      exporters: [file/traces, otlp/jaeger, debug]

    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, attributes, filter/metrics, resource]
      exporters: [file/metrics, prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes, resource]
      exporters: [file/logs, debug]

  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888
