// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// Lifecycle represents a plain enum
type Lifecycle uint8

const (
	LifecycleInit Lifecycle = iota
	LifecycleOnConnect
	LifecycleOnDisconnect
)

