// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

import (
	"github.com/clockworklabs/SpacetimeDB/crates/bindings-go/pkg/spacetimedb"
)

// MiscModuleExport represents a sum type (enum)
type MiscModuleExport interface {
	IsMiscModuleExport() bool
}

// MiscModuleExportTypeAlias represents the TypeAlias variant of MiscModuleExport
// MiscModuleExportTypeAliasVariant represents the TypeAlias variant of MiscModuleExport
type MiscModuleExportTypeAliasVariant struct {
	Value TypeAlias `json:"value" bsatn:"value"`
}

// IsMiscModuleExport implements the MiscModuleExport interface
func (v *MiscModuleExportTypeAliasVariant) IsMiscModuleExport() bool {
	return true
}

