// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// ProductTypeElement represents a product type
type ProductTypeElement struct {
	Name *string `json:"name" bsatn:"name"`
	AlgebraicType AlgebraicType `json:"algebraictype" bsatn:"algebraictype"`
}

