// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// ProductType represents a product type
type ProductType struct {
	Elements []ProductTypeElement `json:"elements" bsatn:"elements"`
}

