// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawReducerDefV9 represents a product type
type RawReducerDefV9 struct {
	Name string `json:"name" bsatn:"name"`
	Params ProductType `json:"params" bsatn:"params"`
	Lifecycle *Lifecycle `json:"lifecycle" bsatn:"lifecycle"`
}

