// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawScopedTypeNameV9 represents a product type
type RawScopedTypeNameV9 struct {
	Scope []string `json:"scope" bsatn:"scope"`
	Name string `json:"name" bsatn:"name"`
}

