// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawIndexDefV9 represents a product type
type RawIndexDefV9 struct {
	Name *string `json:"name" bsatn:"name"`
	AccessorName *string `json:"accessorname" bsatn:"accessorname"`
	Algorithm RawIndexAlgorithm `json:"algorithm" bsatn:"algorithm"`
}

