// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawColumnDefV8 represents a product type
type RawColumnDefV8 struct {
	ColName string `json:"colname" bsatn:"colname"`
	ColType AlgebraicType `json:"coltype" bsatn:"coltype"`
}

