// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

import (
	"github.com/clockworklabs/SpacetimeDB/crates/bindings-go/pkg/spacetimedb"
)

// RawModuleDef represents a sum type (enum)
type RawModuleDef interface {
	IsRawModuleDef() bool
}

// RawModuleDefV8BackCompatVariant represents the V8BackCompat variant of RawModuleDef
type RawModuleDefV8BackCompatVariant struct {
	Value RawModuleDefV8 `json:"value" bsatn:"value"`
}

// IsRawModuleDef implements the RawModuleDef interface
func (v *RawModuleDefV8BackCompatVariant) IsRawModuleDef() bool {
	return true
}

// RawModuleDefV9 represents the V9 variant of RawModuleDef
// RawModuleDefV9Variant represents the V9 variant of RawModuleDef
type RawModuleDefV9Variant struct {
	Value RawModuleDefV9 `json:"value" bsatn:"value"`
}

// IsRawModuleDef implements the RawModuleDef interface
func (v *RawModuleDefV9Variant) IsRawModuleDef() bool {
	return true
}

