// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawModuleDefV9 represents a product type
type RawModuleDefV9 struct {
	Typespace Typespace `json:"typespace" bsatn:"typespace"`
	Tables []RawTableDefV9 `json:"tables" bsatn:"tables"`
	Reducers []RawReducerDefV9 `json:"reducers" bsatn:"reducers"`
	Types []RawTypeDefV9 `json:"types" bsatn:"types"`
	MiscExports []RawMiscModuleExportV9 `json:"miscexports" bsatn:"miscexports"`
	RowLevelSecurity []RawRowLevelSecurityDefV9 `json:"rowlevelsecurity" bsatn:"rowlevelsecurity"`
}

