// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawTypeDefV9 represents a product type
type RawTypeDefV9 struct {
	Name RawScopedTypeNameV9 `json:"name" bsatn:"name"`
	Ty uint32 `json:"ty" bsatn:"ty"`
	CustomOrdering bool `json:"customordering" bsatn:"customordering"`
}

