// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawRowLevelSecurityDefV9 represents a product type
type RawRowLevelSecurityDefV9 struct {
	Sql string `json:"sql" bsatn:"sql"`
}

