// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawScheduleDefV9 represents a product type
type RawScheduleDefV9 struct {
	Name *string `json:"name" bsatn:"name"`
	ReducerName string `json:"reducername" bsatn:"reducername"`
	ScheduledAtColumn uint16 `json:"scheduledatcolumn" bsatn:"scheduledatcolumn"`
}

