// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawUniqueConstraintDataV9 represents a product type
type RawUniqueConstraintDataV9 struct {
	Columns []uint16 `json:"columns" bsatn:"columns"`
}

