// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawConstraintDefV9 represents a product type
type RawConstraintDefV9 struct {
	Name *string `json:"name" bsatn:"name"`
	Data RawConstraintDataV9 `json:"data" bsatn:"data"`
}

