// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// RawConstraintDefV8 represents a product type
type RawConstraintDefV8 struct {
	ConstraintName string `json:"constraintname" bsatn:"constraintname"`
	Constraints uint8 `json:"constraints" bsatn:"constraints"`
	Columns []uint16 `json:"columns" bsatn:"columns"`
}

