// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// ReducerDef represents a product type
type ReducerDef struct {
	Name string `json:"name" bsatn:"name"`
	Args []ProductTypeElement `json:"args" bsatn:"args"`
}

