// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// SumTypeVariant represents a product type
type SumTypeVariant struct {
	Name *string `json:"name" bsatn:"name"`
	AlgebraicType AlgebraicType `json:"algebraictype" bsatn:"algebraictype"`
}

