// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// TableAccess represents a plain enum
type TableAccess uint8

const (
	TableAccessPublic TableAccess = iota
	TableAccessPrivate
)

