// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// TableDesc represents a product type
type TableDesc struct {
	Schema RawTableDefV8 `json:"schema" bsatn:"schema"`
	Data uint32 `json:"data" bsatn:"data"`
}

