// // THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB
package autogen

// TypeAlias represents a product type
type TypeAlias struct {
	Name string `json:"name" bsatn:"name"`
	Ty uint32 `json:"ty" bsatn:"ty"`
}

